error: make git_errno more useful
Don't make git_errno static and add an argument to
git_error_print_stack. If this argument is NULL, it will print the
default stack; otherwise it will print the given stack.

Signed-off-by: Carlos Martín Nieto <carlos@cmartin.tk>